name: AGET
channels:
  - defaults
dependencies:
  - requests=2.25.1
  - nbconvert=6.0.7
  - prompt-toolkit=3.0.18
  - entrypoints=0.3
  - libssh2=1.9.0
  - networkx=2.6.3
  - setuptools=52.0.0
  - sniffio=1.2.0
  - ca-certificates
  - async_generator=1.10
  - pandocfilters=1.4.2
  - pandas=1.2.4
  - jinja2=3.0.1
  - cycler=0.10.0
  - pickleshare=0.7.5
  - jupyterlab=3.0.16
  - cached_property=1.5.2
  - jbig=2.1
  - traitlets=5.0.5
  - emcee=3.1.0
  - pyreadline=2.1
  - tbb=2021.2.0
  - yaml=0.2.5
  - tornado=6.1
  - liblapack=3.9.0
  - xlrd
  - jupyter_server=1.8.0
  - lerc=2.2.1
  - jupyter_console=6.4.0
  - intel-openmp=2021.2.0
  - pip=21.1.1
  - jupyter=1.0.0
  - krb5=1.19.1
  - sympy=1.9
  - chardet=4.0.0
  - cffi=1.14.5
  - numba=0.54.1
  - argon2-cffi=20.1.0
  - json5=0.9.5
  - libdeflate=1.7
  - seaborn=0.11.1
  - nbclient=0.5.3
  - matplotlib-inline=0.1.2
  - prompt_toolkit=3.0.18
  - pytz=2021.1
  - mpmath=1.2.1
  - typing_extensions=3.10.0.0
  - decorator=5.0.9
  - zeromq=4.3.4
  - ipykernel=5.5.5
  - lcms2=2.12
  - ipython=7.24.1
  - libcblas=3.9.0
  - pynndescent=0.5.5
  - bleach=3.3.0
  - schwimmbad=0.3.2
  - pyqtwebengine=5.12.1
  - python-dateutil=2.8.1
  - seaborn=0.11.1
  - lz4-c=1.9.3
  - python=3.7.10
  - open3d=0.13.0
  - idna=2.10
  - notebook=6.4.0
  - matplotlib=3.4.2
  - threadpoolctl=2.1.0
  - pillow=8.2.0
  - cryptography=3.4.7
  - certifi
  - pyopenssl=20.0.1
  - widgetsnbextension=3.5.1
  - addict=2.4.0
  - pyqtchart=5.12
  - zipp=3.4.1
  - mkl=2021.2.0
  - jsonschema=3.2.0
  - statsmodels=0.12.0
  - packaging=20.9
  - babel=2.9.1
  - nbclassic=0.3.1
  - webencodings=0.5.1
  - mistune=0.8.4
  - pyparsing=2.4.7
  - icu=68.1
  - pyyaml=5.4.1
  - xz=5.2.5
  - jedi=0.18.0
  - jupyter_core=4.7.1
  - umap-learn=0.5.2
  - corner=2.1.0
  - backports=1.0
  - llvmlite=0.37.0
  - hdf5=1.10.6
  - jupyter_client=6.1.12
  - scikit-learn=0.24.2
  - wcwidth=0.2.5
  - wheel=0.36.2
  - defusedxml=0.7.1
  - pycparser=2
